#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "ankisyncd"
name = "Anki sync server"
description.en = "Personal Anki sync server (so you can sync against your own server rather than AnkiWeb)"
description.fr = "Serveur de synchronisation Anki personnel (vous pouvez donc synchroniser avec votre propre serveur plutôt qu'avec AnkiWeb)"

version = "2.4.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = " AGPL-3.0"
website = "https://apps.ankiweb.net/"
admindoc = "https://yunohost.org/packaging_apps"
code = "https://github.com/ericgaspar/Anki-sync-server_ynh"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = "not_relevant"

sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/sync"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/ankicommunity/ankicommunity-sync-server/archive/refs/tags/v2.4.0.tar.gz"
    sha256 = "1717f9d95f0a83b10ffb59ece3ff241efc4980181a3290e7834f60eaf5794304"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["collections"]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 27701

    [resources.apt]
    packages = "python3-venv, python3-pip"
